sudo: required

services:
  - docker

env:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_0b56eac220ff_key -iv $encrypted_0b56eac220ff_iv -in burner-amikumar42-99154060596e.json.enc -out burner-amikumar42-99154060596e.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file burner-amikumar42-99154060596e.json
  - gcloud config set project burner-amikumar42
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t amitkumar20491/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amitkumar20491/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on: 
    branch: master